
spring.application.name=SpringBoot_CRUD

spring.datasource.url=jdbc:mysql://localhost:3306/ems
spring.datasource.username=root
spring.datasource.password=saurav67

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
